package com.hibernatepractice.prj;

import javax.persistence.*;

@Entity
@Table(name = "regions")

public class Region {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "region_id")
    private int id;

    @Column(name = "region_name")
    private String name;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

/*
 * @Entity:
 * Marks this class as a JPA entity that will be mapped to a table in the database.
 * 
 * @Table(name = "regions"):
 * Specifies the table name in the database that this entity corresponds to, in this case, the regions table.
 * 
 * @Id:
 * Designates the primary key field for the entity. In this case, id uniquely identifies each Region.
 * 
 * @GeneratedValue(strategy = GenerationType.IDENTITY): 
 * Indicates that the id field will be automatically generated by the database. The GenerationType.IDENTITY strategy implies auto-increment (or similar behavior) for the primary key.
 * 
 * @Column(name = "region_id"):
 * Specifies the column in the database table (region_id) that maps to the id field in this entity.
 * 
 * @Column(name = "region_name"): 
 * Specifies the column in the database table (region_name) that maps to the name field in this entity.
 * 
 * Getters and Setters:
 * Required for accessing and modifying the fields. These methods are essential for JPA to access and manipulate the entity's state.
 */